In [3]:
# File: 1.2 Exercise CreateASearchEngine.ipynb
# Name: Gabriel Valenzuela
# Date: 03/12/2020
# Course: DSC 550 - Data Mining
# Purpose: Creating a 2D array filled with random integers, followed by finding the mean, min, max, and standard
#           deviation. Next, it will sort on a row, on a column, on row 2, and on column 2
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

import numpy as np
import pandas as pd

# 1
# Create an array with random integers
rows, cols = (10,50)
arr = [[np.random.randint(1,500) for i in range(cols)] for j in range(rows)]
# Load into DataFrame
df = pd.DataFrame(arr)
df_sum = pd.DataFrame(arr)
print("Randomized Data Frame")
print(df)
print("\n")

# 2
# Sum of each row, column, and all entries
df_sum.loc['Total',:] = df_sum.sum(axis=0)
df_sum.loc[:,'Total'] = df_sum.sum(axis=1)
print("Sum of each Row, Column, and all Values")
print(df_sum)

# 3
# Minimum of all entries
print("\nMinimum Value: " + str(df.values.min()))

# Maximum of all entries
print("Maximum Value: " + str(df.values.max()))

# Average of all entries
print("Average Value: " + str(df.values.mean()))

# Standard Deviation of all entries
print("Standard Deviation: " + str(df.values.std()) + "\n")

# 4
# Sort dataframe by rows
print("Sort by Row")
print(df.sort_values(by=0, axis=1))
print("\n")
# Sort dataframe by columns
print("Sort by Column")
print(df.sort_values(by=0, axis=0))
print("\n")
# Sort dataframe on row 2
print("Sort by Row 2")
print(df.sort_values(by=2, axis=1))
print("\n")
# Sort dataframe on column 2
print("Sort by Column 2")
print(df.sort_values(by=2, axis=0))

Randomized Data Frame
    0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0  326   57  441   26  294  307  484  457   66  357  ...  235  243  365    1
1  426  239  305    4  414   30  299  378  100  288  ...   18  276  414  480
2  447  220  493  406  363  277   94  293  433  332  ...  234  320  438  156
3  219  202  468   41  242  388   90  403  125  251  ...  400  220  269  204
4  438  116  361  491   12  142  404   60  376  422  ...  303  377   60  332
5  414   94  452  142  161  267  489  173  259  274  ...  392  203  246  392
6  311  184  470  494   74  415   89  146  214  403  ...  204  210  389  295
7   39  188  218  419  239  384   33  144  398  213  ...  374  361  366  431
8  486  169  112   91  314  351  475  416   47  428  ...    2  475   14   31
9  326  349  300  302  232  299  342   15  142   48  ...  136  411  323  104

    44   45   46   47   48   49
0   67  452   88  131  230   53
1  489  385  381   18   64  392
2  459  189  369   91  150  398
3   86  179  204   72  428  120
4   52  353  114  295  271  282
5  324  155  155  348   99  176
6  376   58  268   82  197  125
7  376  114  236  279  227  283
8   15  498  233  150  382  410
9   48  269   32  109   39  272

[10 rows x 50 columns]


Sum of each Row, Column, and all Values
            0       1       2       3       4       5       6       7       8  \
0       326.0    57.0   441.0    26.0   294.0   307.0   484.0   457.0    66.0
1       426.0   239.0   305.0     4.0   414.0    30.0   299.0   378.0   100.0
2       447.0   220.0   493.0   406.0   363.0   277.0    94.0   293.0   433.0
3       219.0   202.0   468.0    41.0   242.0   388.0    90.0   403.0   125.0
4       438.0   116.0   361.0   491.0    12.0   142.0   404.0    60.0   376.0
5       414.0    94.0   452.0   142.0   161.0   267.0   489.0   173.0   259.0
6       311.0   184.0   470.0   494.0    74.0   415.0    89.0   146.0   214.0
7        39.0   188.0   218.0   419.0   239.0   384.0    33.0   144.0   398.0
8       486.0   169.0   112.0    91.0   314.0   351.0   475.0   416.0    47.0
9       326.0   349.0   300.0   302.0   232.0   299.0   342.0    15.0   142.0
Total  3432.0  1818.0  3620.0  2416.0  2345.0  2860.0  2799.0  2485.0  2160.0

            9  ...      41      42      43      44      45      46      47  \
0       357.0  ...   243.0   365.0     1.0    67.0   452.0    88.0   131.0
1       288.0  ...   276.0   414.0   480.0   489.0   385.0   381.0    18.0
2       332.0  ...   320.0   438.0   156.0   459.0   189.0   369.0    91.0
3       251.0  ...   220.0   269.0   204.0    86.0   179.0   204.0    72.0
4       422.0  ...   377.0    60.0   332.0    52.0   353.0   114.0   295.0
5       274.0  ...   203.0   246.0   392.0   324.0   155.0   155.0   348.0
6       403.0  ...   210.0   389.0   295.0   376.0    58.0   268.0    82.0
7       213.0  ...   361.0   366.0   431.0   376.0   114.0   236.0   279.0
8       428.0  ...   475.0    14.0    31.0    15.0   498.0   233.0   150.0
9        48.0  ...   411.0   323.0   104.0    48.0   269.0    32.0   109.0
Total  3016.0  ...  3096.0  2884.0  2426.0  2292.0  2652.0  2080.0  1575.0

           48      49     Total
0       230.0    53.0   12424.0
1        64.0   392.0   12999.0
2       150.0   398.0   14537.0
3       428.0   120.0   12976.0
4       271.0   282.0   12119.0
5        99.0   176.0   13210.0
6       197.0   125.0   11737.0
7       227.0   283.0   13314.0
8       382.0   410.0   12026.0
9        39.0   272.0   13104.0
Total  2087.0  2511.0  128446.0

[11 rows x 51 columns]

Minimum Value: 1
Maximum Value: 499
Average Value: 256.892
Standard Deviation: 141.99635324894794

Sort by Row
    43   17   20   3    22   12   49   1    26   32  ...   13   18   2    45  \
0    1    8    9   26   32   45   53   57   57   59  ...  422  439  441  452
1  480  315  400    4  355  242  392  239   14  113  ...  226  422  305  385
2  156  108  480  406   46  404  398  220  248  458  ...  166  269  493  189
3  204  145  487   41  305  433  120  202  408  358  ...  241  316  468  179
4  332  234  170  491  419  329  282  116  165  429  ...  380  117  361  353
5  392  410  410  142  150  191  176   94  429   89  ...  362   91  452  155
6  295   81  197  494  335  401  125  184  265  238  ...  304   55  470   58
7  431  335  227  419  121  253  283  188  380  294  ...  237  153  218  114
8   31  179   98   91  415  172  410  169  451  344  ...  161  118  112  498
9  104  391  245  302  278  265  272  349   22  414  ...  152  400  300  269

    14   23   7    25   6    19
0  453  456  457  476  484  495
1  147  199  378  117  299   36
2  380  471  293  139   94   20
3  165  265  403  410   90  300
4  273   63   60   69  404   25
5  373   49  173  304  489  485
6  296  229  146   86   89  110
7  396  307  144  445   33  187
8  266   80  416  273  475  407
9  376  427   15  457  342  287

[10 rows x 50 columns]


Sort by Column
    0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
7   39  188  218  419  239  384   33  144  398  213  ...  374  361  366  431
3  219  202  468   41  242  388   90  403  125  251  ...  400  220  269  204
6  311  184  470  494   74  415   89  146  214  403  ...  204  210  389  295
0  326   57  441   26  294  307  484  457   66  357  ...  235  243  365    1
9  326  349  300  302  232  299  342   15  142   48  ...  136  411  323  104
5  414   94  452  142  161  267  489  173  259  274  ...  392  203  246  392
1  426  239  305    4  414   30  299  378  100  288  ...   18  276  414  480
4  438  116  361  491   12  142  404   60  376  422  ...  303  377   60  332
2  447  220  493  406  363  277   94  293  433  332  ...  234  320  438  156
8  486  169  112   91  314  351  475  416   47  428  ...    2  475   14   31

    44   45   46   47   48   49
7  376  114  236  279  227  283
3   86  179  204   72  428  120
6  376   58  268   82  197  125
0   67  452   88  131  230   53
9   48  269   32  109   39  272
5  324  155  155  348   99  176
1  489  385  381   18   64  392
4   52  353  114  295  271  282
2  459  189  369   91  150  398
8   15  498  233  150  382  410

[10 rows x 50 columns]


Sort by Row 2
    28   19   33   22   38   47   6    17   25   48  ...   8    42   0    32  \
0   80  495  389   32   98  131  484    8  476  230  ...   66  365  326   59
1  352   36  312  355  132   18  299  315  117   64  ...  100  414  426  113
2   17   20   31   46   88   91   94  108  139  150  ...  433  438  447  458
3  365  300  225  305  393   72   90  145  410  428  ...  125  269  219  358
4   27   25  463  419  332  295  404  234   69  271  ...  376   60  438  429
5  285  485  499  150  193  348  489  410  304   99  ...  259  246  414   89
6  117  110  158  335  329   82   89   81   86  197  ...  214  389  311  238
7  172  187  301  121  290  279   33  335  445  227  ...  398  366   39  294
8  261  407  193  415   25  150  475  179  273  382  ...   47   14  486  344
9  410  287  423  278  488  109  342  391  457   39  ...  142  323  326  414

    44   23   20   15   2    37
0   67  456    9  392  441  329
1  489  199  400  328  305  489
2  459  471  480  484  493  494
3   86  265  487  169  468  490
4   52   63  170  147  361  350
5  324   49  410   18  452  472
6  376  229  197  281  470    7
7  376  307  227  462  218  200
8   15   80   98   82  112  115
9   48  427  245   11  300   94

[10 rows x 50 columns]


Sort by Column 2
    0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
8  486  169  112   91  314  351  475  416   47  428  ...    2  475   14   31
7   39  188  218  419  239  384   33  144  398  213  ...  374  361  366  431
9  326  349  300  302  232  299  342   15  142   48  ...  136  411  323  104
1  426  239  305    4  414   30  299  378  100  288  ...   18  276  414  480
4  438  116  361  491   12  142  404   60  376  422  ...  303  377   60  332
0  326   57  441   26  294  307  484  457   66  357  ...  235  243  365    1
5  414   94  452  142  161  267  489  173  259  274  ...  392  203  246  392
3  219  202  468   41  242  388   90  403  125  251  ...  400  220  269  204
6  311  184  470  494   74  415   89  146  214  403  ...  204  210  389  295
2  447  220  493  406  363  277   94  293  433  332  ...  234  320  438  156

    44   45   46   47   48   49
8   15  498  233  150  382  410
7  376  114  236  279  227  283
9   48  269   32  109   39  272
1  489  385  381   18   64  392
4   52  353  114  295  271  282
0   67  452   88  131  230   53
5  324  155  155  348   99  176
3   86  179  204   72  428  120
6  376   58  268   82  197  125
2  459  189  369   91  150  398

[10 rows x 50 columns]